version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/DockerFile
    container_name: laravel_app_2
    volumes:
      - .:/var/www
    networks:
      - laravel_2
    depends_on:
      - mysql

  webserver:
    image: nginx:alpine
    container_name: nginx_web_2
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel_2

  mysql:
    image: mysql:8.0
    container_name: mysql_db_2
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: test_query
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - db_data_2:/var/lib/mysql
    networks:
      - laravel_2

networks:
  laravel_2:

volumes:
  db_data_2:
